stages:
  - test

test_job:
  stage: test
  tags:
    - server-tag
  script:
    - docker-compose build --no-cache
    - docker-compose up -d db
    - docker-compose run test
    - docker-compose kill
    - docker-compose rm -f
  only:
    refs:
      - master
