version: '3'

services:
  test:
    build: .

  db:
    image: mariadb:10.4
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    volumes:
      - ./tests/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
